// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_beginner = new UnifiedAchievement("Beginner",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIrZD3kukYEAIQAQ"
#else
            "Beginner"
#endif
            );

        public static UnifiedAchievement Beginner
        {
            get { return s_beginner; }
        }

        private static readonly UnifiedAchievement s_intermediate = new UnifiedAchievement("Intermediate",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIrZD3kukYEAIQAg"
#else
            "Intermediate"
#endif
            );

        public static UnifiedAchievement Intermediate
        {
            get { return s_intermediate; }
        }

        private static readonly UnifiedAchievement s_prodigy = new UnifiedAchievement("Prodigy",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIrZD3kukYEAIQAw"
#else
            "Prodigy"
#endif
            );

        public static UnifiedAchievement Prodigy
        {
            get { return s_prodigy; }
        }

        private static readonly UnifiedAchievement s_savant = new UnifiedAchievement("Savant",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIrZD3kukYEAIQBA"
#else
            "Savant"
#endif
            );

        public static UnifiedAchievement Savant
        {
            get { return s_savant; }
        }

        private static readonly UnifiedAchievement s_escapeMaster = new UnifiedAchievement("EscapeMaster",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIrZD3kukYEAIQBQ"
#else
            "EscapeMaster"
#endif
            );

        public static UnifiedAchievement EscapeMaster
        {
            get { return s_escapeMaster; }
        }

        private static readonly UnifiedAchievement s_superHero = new UnifiedAchievement("SuperHero",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIrZD3kukYEAIQBg"
#else
            "SuperHero"
#endif
            );

        public static UnifiedAchievement SuperHero
        {
            get { return s_superHero; }
        }

        private static readonly UnifiedAchievement s_nextToGod = new UnifiedAchievement("NextToGod",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIrZD3kukYEAIQBw"
#else
            "NextToGod"
#endif
            );

        public static UnifiedAchievement NextToGod
        {
            get { return s_nextToGod; }
        }

        private static readonly UnifiedAchievement s_theGodRunner = new UnifiedAchievement("TheGodRunner",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIrZD3kukYEAIQCA"
#else
            "TheGodRunner"
#endif
            );

        public static UnifiedAchievement TheGodRunner
        {
            get { return s_theGodRunner; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_beginner,
            s_intermediate,
            s_prodigy,
            s_savant,
            s_escapeMaster,
            s_superHero,
            s_nextToGod,
            s_theGodRunner,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "Beginner", s_beginner },
            { "Intermediate", s_intermediate },
            { "Prodigy", s_prodigy },
            { "Savant", s_savant },
            { "EscapeMaster", s_escapeMaster },
            { "SuperHero", s_superHero },
            { "NextToGod", s_nextToGod },
            { "TheGodRunner", s_theGodRunner },
        };
    }
}
